In [2]:
import numpy as np

In [3]:
production = np.array([1 , 2 ,3 ,4 , 5])
print(production)

[1 2 3 4 5]


In [4]:
production = np.array([1 , 2 , 3, 4 , 5])

high_production = production[production>2]      #boolean filtering

print(high_production)

[3 4 5]


In [5]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])
print(data.shape)

(4, 3)


In [6]:
x = data[: , 0:2]
print(x)

[[10 30]
 [12 35]
 [ 9 40]
 [11 32]]


In [7]:
y = data[: , 2]
print(y)

[4200 4300 3900 4100]


In [8]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

error = actual - predicted

print(error)

[  50 -100   50  100]


In [9]:
absolute_error = np.abs(error)

print(absolute_error)

[ 50 100  50 100]


In [10]:
mae = np.mean(absolute_error)

print(mae)

75.0


In [11]:
pressure = np.array([10, 12, 9, 11])

predicted_production = 3000 + 100 * pressure

print(predicted_production)

[4000 4200 3900 4100]


In [12]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

In [13]:
error = actual - predicted
print(error)

[  50 -100   50  100]


In [14]:
abs_error = abs(actual - predicted)
print(abs_error)

[ 50 100  50 100]


In [15]:
mae = np.mean(abs_error)
print(mae)

75.0


In [18]:
a = np.arange(1 , 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
b = np.zeros(5)

c = np.ones(10)

print(b , c) 

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
d = np.linspace(1 , 40 , 10)
print(d)

[ 1.          5.33333333  9.66666667 14.         18.33333333 22.66666667
 27.         31.33333333 35.66666667 40.        ]


In [22]:
print(data.ndim)

2


In [23]:
print(data.size)

12


In [25]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])

features = data[: , 0:2]
result = data[: , 2]

print("Features : " , features)

print("results : " , result)    #feature rows must equal to results length 

Features :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]]
results :  [4200 4300 3900 4100]


In [26]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

x = data[: , 0:2]

y = data[: , 2]

print("Featues : " , x)
print("Result : " , y)

Featues :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]
 [13 29]]
Result :  [4200 4300 3900 4100 4500]
