In [2]:
import numpy as np

In [3]:
production = np.array([1 , 2 ,3 ,4 , 5])
print(production)

[1 2 3 4 5]


In [4]:
production = np.array([1 , 2 , 3, 4 , 5])

high_production = production[production>2]      #boolean filtering

print(high_production)

[3 4 5]


In [5]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])
print(data.shape)

(4, 3)


In [6]:
x = data[: , 0:2]
print(x)

[[10 30]
 [12 35]
 [ 9 40]
 [11 32]]


In [7]:
y = data[: , 2]
print(y)

[4200 4300 3900 4100]


In [8]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

error = actual - predicted

print(error)

[  50 -100   50  100]


In [9]:
absolute_error = np.abs(error)

print(absolute_error)

[ 50 100  50 100]


In [10]:
mae = np.mean(absolute_error)

print(mae)

75.0


In [11]:
pressure = np.array([10, 12, 9, 11])

predicted_production = 3000 + 100 * pressure

print(predicted_production)

[4000 4200 3900 4100]


In [12]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

In [13]:
error = actual - predicted
print(error)

[  50 -100   50  100]


In [14]:
abs_error = abs(actual - predicted)
print(abs_error)

[ 50 100  50 100]


In [15]:
mae = np.mean(abs_error)
print(mae)

75.0


In [18]:
a = np.arange(1 , 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
b = np.zeros(5)

c = np.ones(10)

print(b , c) 

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
d = np.linspace(1 , 40 , 10)
print(d)

[ 1.          5.33333333  9.66666667 14.         18.33333333 22.66666667
 27.         31.33333333 35.66666667 40.        ]


In [22]:
print(data.ndim)

2


In [23]:
print(data.size)

12


In [25]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])

features = data[: , 0:2]
result = data[: , 2]

print("Features : " , features)

print("results : " , result)    #feature rows must equal to results length 

Features :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]]
results :  [4200 4300 3900 4100]


In [26]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

x = data[: , 0:2]

y = data[: , 2]

print("Featues : " , x)
print("Result : " , y)

Featues :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]
 [13 29]]
Result :  [4200 4300 3900 4100 4500]


In [27]:
production = np.array([4200 , 4300 , 3900 , 4100 , 4500])

print(production[0 : 5 : 2])

[4200 3900 4500]


In [28]:
print(production[::-1])

[4500 4100 3900 4300 4200]


In [29]:
production = np.array([4200, 4300, 3900, 4100, 4500])

subset = production[0:3]
subset[0] = 9999

print(subset)
print(production)

[9999 4300 3900]
[9999 4300 3900 4100 4500]


In [30]:
production = np.array([4200, 4300, 3900, 4100, 4500])

subset = production[0:3].copy()
subset[0] = 9999

print(subset)
print(production)

[9999 4300 3900]
[4200 4300 3900 4100 4500]


In [31]:
print(production)

[4200 4300 3900 4100 4500]


In [32]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

production = data[: , 2]
high_production = production[production>=4200]
print(high_production)

[4200 4300 4500]


In [33]:

data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

X = data[:, 0:2]
y = data[:, 2]

pressure = X[:, 0]

predicted = 3000 + 100 * pressure

error = y - predicted
absolute_error = np.abs(error)

bad_rows = data[absolute_error > 100]

print("Actual production:")
print(y)

print("Predicted production:")
print(predicted)

print("Absolute error:")
print(absolute_error)

print("Rows with error greater than 100:")
print(bad_rows)

Actual production:
[4200 4300 3900 4100 4500]
Predicted production:
[4000 4200 3900 4100 4300]
Absolute error:
[200 100   0   0 200]
Rows with error greater than 100:
[[  10   30 4200]
 [  13   29 4500]]


In [34]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

X = data[:, 0:2]
y = data[:, 2]

pressure = X[:, 0]

predicted = 3000 + 100 * pressure

error = y - predicted
absolute_error = np.abs(error)

bad_prediction_rows = data[absolute_error > 100]

labels = np.where(absolute_error <= 100, "Good", "Bad")

print("Features X:")
print(X)

print("Target y:")
print(y)

print("Predicted:")
print(predicted)

print("Error:")
print(error)

print("Absolute Error:")
print(absolute_error)

print("Prediction Labels:")
print(labels)

print("Rows with bad predictions:")
print(bad_prediction_rows)

Features X:
[[10 30]
 [12 35]
 [ 9 40]
 [11 32]
 [13 29]]
Target y:
[4200 4300 3900 4100 4500]
Predicted:
[4000 4200 3900 4100 4300]
Error:
[200 100   0   0 200]
Absolute Error:
[200 100   0   0 200]
Prediction Labels:
['Bad' 'Good' 'Good' 'Good' 'Bad']
Rows with bad predictions:
[[  10   30 4200]
 [  13   29 4500]]


In [35]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])
coloumn_mean = np.mean(data , axis = 0)

print(coloumn_mean)

[  11.    33.2 4200. ]


In [36]:
row_mean = np.mean(data , axis = 1)
print(row_mean)

[1413.33333333 1449.         1316.33333333 1381.         1514.        ]


In [37]:
pressure = np.array([10, 12, 9, 11, 13])

scaled_value = (pressure - np.mean(pressure)) / np.std(pressure)

print(np.round(scaled_value , 2))

[-0.71  0.71 -1.41  0.    1.41]


In [38]:
features = np.array([10, 30])
weights = np.array([100, -5])

prediction = np.dot(features, weights)

print(prediction)

850


In [39]:
actual = np.array([4200, 4300, 3900, 4100, 4500])
predicted = np.array([4000, 4200, 3900, 4100, 4300])

error = actual - predicted
absolute_error = np.abs(error)
squared_error = error ** 2

mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
mape = np.mean(np.abs(error / actual)) * 100

ss_res = np.sum((actual - predicted) ** 2)
ss_total = np.sum((actual - np.mean(actual)) ** 2)
r2 = 1 - (ss_res / ss_total)

print("Actual:", actual)
print("Predicted:", predicted)
print("Error:", error)
print("Absolute Error:", absolute_error)
print("Squared Error:", squared_error)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", np.round(rmse, 2))
print("MAPE:", np.round(mape, 2), "%")
print("R²:", np.round(r2, 3))

Actual: [4200 4300 3900 4100 4500]
Predicted: [4000 4200 3900 4100 4300]
Error: [200 100   0   0 200]
Absolute Error: [200 100   0   0 200]
Squared Error: [40000 10000     0     0 40000]
MAE: 100.0
MSE: 18000.0
RMSE: 134.16
MAPE: 2.31 %
R²: 0.55


In [40]:
import numpy as np

actual = np.array([4200, 4300, 3900, 4100, 4500])
predicted = np.array([4000, 4200, 3900, 4100, 4300])

error = actual - predicted
absolute_error = np.abs(error)
squared_error = error ** 2

mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
mape = np.mean(np.abs(error / actual)) * 100

ss_res = np.sum((actual - predicted) ** 2)
ss_total = np.sum((actual - np.mean(actual)) ** 2)
r2 = 1 - (ss_res / ss_total)

print("Error:", error)
print("Absolute Error:", absolute_error)
print("Squared Error:", squared_error)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", np.round(rmse, 2))
print("MAPE:", np.round(mape, 2), "%")
print("R²:", np.round(r2, 3))

if mape <= 5:
    print("Excellent model")
elif mape <= 10:
    print("Acceptable model")
else:
    print("Poor model")

Error: [200 100   0   0 200]
Absolute Error: [200 100   0   0 200]
Squared Error: [40000 10000     0     0 40000]
MAE: 100.0
MSE: 18000.0
RMSE: 134.16
MAPE: 2.31 %
R²: 0.55
Excellent model
