In [1]:
import numpy as np

In [2]:
production = np.array([1 , 2 ,3 ,4 , 5])
print(production)

[1 2 3 4 5]


In [4]:
production = np.array([1 , 2 , 3, 4 , 5])

high_production = production[production>2]      #boolean filtering

print(high_production)

[3 4 5]


In [5]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])
print(data.shape)

(4, 3)


In [6]:
x = data[: , 0:2]
print(x)

[[10 30]
 [12 35]
 [ 9 40]
 [11 32]]


In [7]:
y = data[: , 2]
print(y)

[4200 4300 3900 4100]


In [8]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

error = actual - predicted

print(error)

[  50 -100   50  100]


In [9]:
absolute_error = np.abs(error)

print(absolute_error)

[ 50 100  50 100]


In [10]:
mae = np.mean(absolute_error)

print(mae)

75.0


In [11]:
pressure = np.array([10, 12, 9, 11])

predicted_production = 3000 + 100 * pressure

print(predicted_production)

[4000 4200 3900 4100]


In [12]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

In [13]:
error = actual - predicted
print(error)

[  50 -100   50  100]


In [14]:
abs_error = abs(actual - predicted)
print(abs_error)

[ 50 100  50 100]


In [15]:
mae = np.mean(abs_error)
print(mae)

75.0
