In [2]:
import numpy as np

In [3]:
production = np.array([1 , 2 ,3 ,4 , 5])
print(production)

[1 2 3 4 5]


In [4]:
production = np.array([1 , 2 , 3, 4 , 5])

high_production = production[production>2]      #boolean filtering

print(high_production)

[3 4 5]


In [5]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])
print(data.shape)

(4, 3)


In [6]:
x = data[: , 0:2]
print(x)

[[10 30]
 [12 35]
 [ 9 40]
 [11 32]]


In [7]:
y = data[: , 2]
print(y)

[4200 4300 3900 4100]


In [8]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

error = actual - predicted

print(error)

[  50 -100   50  100]


In [9]:
absolute_error = np.abs(error)

print(absolute_error)

[ 50 100  50 100]


In [10]:
mae = np.mean(absolute_error)

print(mae)

75.0


In [11]:
pressure = np.array([10, 12, 9, 11])

predicted_production = 3000 + 100 * pressure

print(predicted_production)

[4000 4200 3900 4100]


In [12]:
actual = np.array([4200, 4300, 3900, 4100])
predicted = np.array([4150, 4400, 3850, 4000])

In [13]:
error = actual - predicted
print(error)

[  50 -100   50  100]


In [14]:
abs_error = abs(actual - predicted)
print(abs_error)

[ 50 100  50 100]


In [15]:
mae = np.mean(abs_error)
print(mae)

75.0


In [18]:
a = np.arange(1 , 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
b = np.zeros(5)

c = np.ones(10)

print(b , c) 

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
d = np.linspace(1 , 40 , 10)
print(d)

[ 1.          5.33333333  9.66666667 14.         18.33333333 22.66666667
 27.         31.33333333 35.66666667 40.        ]


In [22]:
print(data.ndim)

2


In [23]:
print(data.size)

12


In [25]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100]
])

features = data[: , 0:2]
result = data[: , 2]

print("Features : " , features)

print("results : " , result)    #feature rows must equal to results length 

Features :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]]
results :  [4200 4300 3900 4100]


In [26]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

x = data[: , 0:2]

y = data[: , 2]

print("Featues : " , x)
print("Result : " , y)

Featues :  [[10 30]
 [12 35]
 [ 9 40]
 [11 32]
 [13 29]]
Result :  [4200 4300 3900 4100 4500]


In [27]:
production = np.array([4200 , 4300 , 3900 , 4100 , 4500])

print(production[0 : 5 : 2])

[4200 3900 4500]


In [28]:
print(production[::-1])

[4500 4100 3900 4300 4200]


In [29]:
production = np.array([4200, 4300, 3900, 4100, 4500])

subset = production[0:3]
subset[0] = 9999

print(subset)
print(production)

[9999 4300 3900]
[9999 4300 3900 4100 4500]


In [30]:
production = np.array([4200, 4300, 3900, 4100, 4500])

subset = production[0:3].copy()
subset[0] = 9999

print(subset)
print(production)

[9999 4300 3900]
[4200 4300 3900 4100 4500]


In [31]:
print(production)

[4200 4300 3900 4100 4500]


In [32]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

production = data[: , 2]
high_production = production[production>=4200]
print(high_production)

[4200 4300 4500]


In [33]:

data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

X = data[:, 0:2]
y = data[:, 2]

pressure = X[:, 0]

predicted = 3000 + 100 * pressure

error = y - predicted
absolute_error = np.abs(error)

bad_rows = data[absolute_error > 100]

print("Actual production:")
print(y)

print("Predicted production:")
print(predicted)

print("Absolute error:")
print(absolute_error)

print("Rows with error greater than 100:")
print(bad_rows)

Actual production:
[4200 4300 3900 4100 4500]
Predicted production:
[4000 4200 3900 4100 4300]
Absolute error:
[200 100   0   0 200]
Rows with error greater than 100:
[[  10   30 4200]
 [  13   29 4500]]


In [34]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])

X = data[:, 0:2]
y = data[:, 2]

pressure = X[:, 0]

predicted = 3000 + 100 * pressure

error = y - predicted
absolute_error = np.abs(error)

bad_prediction_rows = data[absolute_error > 100]

labels = np.where(absolute_error <= 100, "Good", "Bad")

print("Features X:")
print(X)

print("Target y:")
print(y)

print("Predicted:")
print(predicted)

print("Error:")
print(error)

print("Absolute Error:")
print(absolute_error)

print("Prediction Labels:")
print(labels)

print("Rows with bad predictions:")
print(bad_prediction_rows)

Features X:
[[10 30]
 [12 35]
 [ 9 40]
 [11 32]
 [13 29]]
Target y:
[4200 4300 3900 4100 4500]
Predicted:
[4000 4200 3900 4100 4300]
Error:
[200 100   0   0 200]
Absolute Error:
[200 100   0   0 200]
Prediction Labels:
['Bad' 'Good' 'Good' 'Good' 'Bad']
Rows with bad predictions:
[[  10   30 4200]
 [  13   29 4500]]


In [35]:
data = np.array([
    [10, 30, 4200],
    [12, 35, 4300],
    [9, 40, 3900],
    [11, 32, 4100],
    [13, 29, 4500]
])
coloumn_mean = np.mean(data , axis = 0)

print(coloumn_mean)

[  11.    33.2 4200. ]


In [36]:
row_mean = np.mean(data , axis = 1)
print(row_mean)

[1413.33333333 1449.         1316.33333333 1381.         1514.        ]


In [37]:
pressure = np.array([10, 12, 9, 11, 13])

scaled_value = (pressure - np.mean(pressure)) / np.std(pressure)

print(np.round(scaled_value , 2))

[-0.71  0.71 -1.41  0.    1.41]


In [38]:
features = np.array([10, 30])
weights = np.array([100, -5])

prediction = np.dot(features, weights)

print(prediction)

850


In [39]:
actual = np.array([4200, 4300, 3900, 4100, 4500])
predicted = np.array([4000, 4200, 3900, 4100, 4300])

error = actual - predicted
absolute_error = np.abs(error)
squared_error = error ** 2

mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
mape = np.mean(np.abs(error / actual)) * 100

ss_res = np.sum((actual - predicted) ** 2)
ss_total = np.sum((actual - np.mean(actual)) ** 2)
r2 = 1 - (ss_res / ss_total)

print("Actual:", actual)
print("Predicted:", predicted)
print("Error:", error)
print("Absolute Error:", absolute_error)
print("Squared Error:", squared_error)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", np.round(rmse, 2))
print("MAPE:", np.round(mape, 2), "%")
print("R²:", np.round(r2, 3))

Actual: [4200 4300 3900 4100 4500]
Predicted: [4000 4200 3900 4100 4300]
Error: [200 100   0   0 200]
Absolute Error: [200 100   0   0 200]
Squared Error: [40000 10000     0     0 40000]
MAE: 100.0
MSE: 18000.0
RMSE: 134.16
MAPE: 2.31 %
R²: 0.55


In [40]:
import numpy as np

actual = np.array([4200, 4300, 3900, 4100, 4500])
predicted = np.array([4000, 4200, 3900, 4100, 4300])

error = actual - predicted
absolute_error = np.abs(error)
squared_error = error ** 2

mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
mape = np.mean(np.abs(error / actual)) * 100

ss_res = np.sum((actual - predicted) ** 2)
ss_total = np.sum((actual - np.mean(actual)) ** 2)
r2 = 1 - (ss_res / ss_total)

print("Error:", error)
print("Absolute Error:", absolute_error)
print("Squared Error:", squared_error)
print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", np.round(rmse, 2))
print("MAPE:", np.round(mape, 2), "%")
print("R²:", np.round(r2, 3))

if mape <= 5:
    print("Excellent model")
elif mape <= 10:
    print("Acceptable model")
else:
    print("Poor model")

Error: [200 100   0   0 200]
Absolute Error: [200 100   0   0 200]
Squared Error: [40000 10000     0     0 40000]
MAE: 100.0
MSE: 18000.0
RMSE: 134.16
MAPE: 2.31 %
R²: 0.55
Excellent model


In [43]:
import numpy as np

pressure = np.array([10, 12, 9, 11, 13])
water_cut = np.array([30, 35, 40, 32, 29])
choke_size = np.array([45, 50, 42, 47, 52])
production = np.array([4200, 4300, 3900, 4100, 4500])

data = np.column_stack([pressure , water_cut , choke_size , production])
print(data)

[[  10   30   45 4200]
 [  12   35   50 4300]
 [   9   40   42 3900]
 [  11   32   47 4100]
 [  13   29   52 4500]]


In [44]:
a = np.array([[10, 30],
              [12, 35]])

b = np.array([[9, 40],
              [11, 32]])

com_data = np.concatenate((a , b) , axis = 0)
print(com_data)


[[10 30]
 [12 35]
 [ 9 40]
 [11 32]]


In [45]:

pressure = np.array([10, 12, 9, 11, 13])
water_cut = np.array([30, 35, 40, 32, 29])
choke_size = np.array([45, 50, 42, 47, 52])
production = np.array([4200, 4300, 3900, 4100, 4500])

X = np.column_stack((pressure, water_cut, choke_size))
y = production

data = np.column_stack((X, y))

print("Feature matrix X:")
print(X)

print("Target y:")
print(y)

print("Full dataset:")
print(data)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Data shape:", data.shape)

Feature matrix X:
[[10 30 45]
 [12 35 50]
 [ 9 40 42]
 [11 32 47]
 [13 29 52]]
Target y:
[4200 4300 3900 4100 4500]
Full dataset:
[[  10   30   45 4200]
 [  12   35   50 4300]
 [   9   40   42 3900]
 [  11   32   47 4100]
 [  13   29   52 4500]]
X shape: (5, 3)
y shape: (5,)
Data shape: (5, 4)


In [46]:
data = np.array([
    [10, 30, 45, 4200],
    [12, 35, 50, 4300],
    [9, 40, 42, 3900],
    [11, 32, 47, 4100],
    [13, 29, 52, 4500],
    [14, 28, 55, 4600],
    [8, 42, 40, 3700],
    [15, 27, 56, 4700],
    [10, 36, 44, 4050],
    [12, 33, 49, 4350]
])
X = data[:, 0:3]
y = data[:, 3]

print("X:")
print(X)

print("y:")
print(y)

print("X shape:", X.shape)
print("y shape:", y.shape)
X_train = X[:8]
y_train = y[:8]

X_test = X[8:]
y_test = y[8:]
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X:
[[10 30 45]
 [12 35 50]
 [ 9 40 42]
 [11 32 47]
 [13 29 52]
 [14 28 55]
 [ 8 42 40]
 [15 27 56]
 [10 36 44]
 [12 33 49]]
y:
[4200 4300 3900 4100 4500 4600 3700 4700 4050 4350]
X shape: (10, 3)
y shape: (10,)
X_train shape: (8, 3)
y_train shape: (8,)
X_test shape: (2, 3)
y_test shape: (2,)


In [48]:
import numpy as np

X = np.array([
    [10, 30, 45],
    [12, 35, 50],
    [9, 40, 42],
    [11, 32, 47],
    [13, 29, 52],
    [14, 28, 55],
    [8, 42, 40],
    [15, 27, 56],
    [10, 36, 44],
    [12, 33, 49]
])

water = X[: , 0]
print(water)

[10 12  9 11 13 14  8 15 10 12]


In [49]:
min_water = np.min(water)
print(min_water)

8


In [51]:
min_values = np.min(X , axis = 0)
print(min_values)

[ 8 27 40]


In [52]:

X_train = np.array([
    [10, 30, 45],
    [12, 35, 50],
    [9, 40, 42],
    [11, 32, 47],
    [13, 29, 52],
    [14, 28, 55],
    [8, 42, 40],
    [15, 27, 56]
])

X_test = np.array([
    [10, 36, 44],
    [12, 33, 49]
])

train_mean = np.mean(X_train, axis=0)
train_std = np.std(X_train, axis=0)

X_train_scaled = (X_train - train_mean) / train_std
X_test_scaled = (X_test - train_mean) / train_std

print("Training mean:", train_mean)
print("Training std:", np.round(train_std, 2))

print("Scaled training data:")
print(np.round(X_train_scaled, 2))

print("Scaled testing data:")
print(np.round(X_test_scaled, 2))

Training mean: [11.5   32.875 48.375]
Training std: [2.29 5.25 5.5 ]
Scaled training data:
[[-0.65 -0.55 -0.61]
 [ 0.22  0.4   0.3 ]
 [-1.09  1.36 -1.16]
 [-0.22 -0.17 -0.25]
 [ 0.65 -0.74  0.66]
 [ 1.09 -0.93  1.2 ]
 [-1.53  1.74 -1.52]
 [ 1.53 -1.12  1.39]]
Scaled testing data:
[[-0.65  0.59 -0.8 ]
 [ 0.22  0.02  0.11]]


In [53]:
import numpy as np

features = np.array([10, 30, 45])

In [54]:
import numpy as np

X = np.array([
    [10, 30, 45],
    [12, 35, 50],
    [9, 40, 42],
    [11, 32, 47],
    [13, 29, 52]
])

actual = np.array([4200, 4300, 3900, 4100, 4500])

weights = np.array([100, -5, 20])
intercept = 2500

predicted = intercept + np.dot(X, weights)

error = actual - predicted
absolute_error = np.abs(error)
mae = np.mean(absolute_error)

print("X:")
print(X)

print("Weights:", weights)
print("Intercept:", intercept)

print("Predicted:", predicted)
print("Actual:", actual)

print("Error:", error)
print("Absolute Error:", absolute_error)
print("MAE:", mae)

if mae <= 100:
    print("Good model")
else:
    print("Model needs improvement")

X:
[[10 30 45]
 [12 35 50]
 [ 9 40 42]
 [11 32 47]
 [13 29 52]]
Weights: [100  -5  20]
Intercept: 2500
Predicted: [4250 4525 4040 4380 4695]
Actual: [4200 4300 3900 4100 4500]
Error: [ -50 -225 -140 -280 -195]
Absolute Error: [ 50 225 140 280 195]
MAE: 178.0
Model needs improvement


In [55]:
rng = np.random.default_rng(42)

numbers = rng.random(5)

print(numbers)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


In [58]:
rng = np.random.default_rng(42)
a = rng.integers(1 , 10 , size = 5)
print(a)

[1 7 6 4 4]


In [59]:
rng = np.random.default_rng(42)

areas = np.array(["North", "South", "East", "West"])

selected = rng.choice(areas, size=3)

print(selected)

['North' 'West' 'East']


In [60]:
import numpy as np

rng = np.random.default_rng(42)

pressure = rng.integers(8, 16, size=10)
water_cut = rng.integers(25, 45, size=10)
choke_size = rng.integers(40, 60, size=10)

production = 2500 + 100 * pressure - 5 * water_cut + 20 * choke_size

noise = rng.normal(loc=0, scale=100, size=10)
production_noisy = production + noise

X = np.column_stack((pressure, water_cut, choke_size))
y = production_noisy

indices = rng.permutation(len(X))

X_shuffled = X[indices]
y_shuffled = y[indices]

print("X:")
print(X)

print("y:")
print(np.round(y, 2))

print("Shuffled X:")
print(X_shuffled)

print("Shuffled y:")
print(np.round(y_shuffled, 2))

X:
[[ 8 35 50]
 [14 44 47]
 [13 39 43]
 [11 40 58]
 [11 39 55]
 [14 40 52]
 [ 8 35 48]
 [13 27 56]
 [ 9 41 50]
 [ 8 34 48]]
y:
[4039.07 4656.88 4369.11 4647.85 4500.01 4721.51 4016.91 4907.25 4179.55
 4047.17]
Shuffled X:
[[ 8 35 48]
 [11 40 58]
 [ 9 41 50]
 [13 39 43]
 [ 8 34 48]
 [14 40 52]
 [14 44 47]
 [13 27 56]
 [11 39 55]
 [ 8 35 50]]
Shuffled y:
[4016.91 4647.85 4179.55 4369.11 4047.17 4721.51 4656.88 4907.25 4500.01
 4039.07]


In [63]:
data = np.array([
    [10, 30, 45, 4200],
    [12, 35, 50, 4300],
    [9, 40, 42, 3900],
    [11, 32, 47, 4100],
    [13, 29, 52, 4500],
    [14, 28, 55, 4600],
    [8, 42, 40, 3700],
    [15, 27, 56, 4700],
    [10, 36, 44, 4050],
    [12, 33, 49, 4350]
], dtype=float)

In [64]:
print(data.shape)

(10, 4)


In [67]:
X = data[: , 0:3]
Y = data[: , 3]

print("X shape : " , X.shape)
print("Y shape : " , Y.shape)

X shape :  (10, 3)
Y shape :  (10,)


In [68]:
rng = np.random.default_rng(42)

indices = rng.permutation(len(data))

shuffled_data = data[indices]
print(shuffled_data)

[[  14.   28.   55. 4600.]
 [   8.   42.   40. 3700.]
 [  10.   30.   45. 4200.]
 [  15.   27.   56. 4700.]
 [  11.   32.   47. 4100.]
 [   9.   40.   42. 3900.]
 [  13.   29.   52. 4500.]
 [  12.   33.   49. 4350.]
 [  12.   35.   50. 4300.]
 [  10.   36.   44. 4050.]]


In [69]:
train_size = int(0.8 * len(shuffled_data))

train_data = shuffled_data[:train_size]
test_data = shuffled_data[train_size:]

X_train = train_data[:, 0:3]
y_train = train_data[:, 3]

X_test = test_data[:, 0:3]
y_test = test_data[:, 3]

In [70]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8, 3)
y_train shape: (8,)
X_test shape: (2, 3)
y_test shape: (2,)


In [ ]:
import numpy as np

# 1. Create dataset
data = np.array([
    [10, 30, 45, 4200],
    [12, 35, 50, 4300],
    [9, 40, 42, 3900],
    [11, 32, 47, 4100],
    [13, 29, 52, 4500],
    [14, 28, 55, 4600],
    [8, 42, 40, 3700],
    [15, 27, 56, 4700],
    [10, 36, 44, 4050],
    [12, 33, 49, 4350]
], dtype=float)

print("Original data shape:", data.shape)

# 2. Shuffle data
rng = np.random.default_rng(42)

indices = rng.permutation(len(data))
shuffled_data = data[indices]

# 3. Train-test split
train_size = int(0.8 * len(shuffled_data))

train_data = shuffled_data[:train_size]
test_data = shuffled_data[train_size:]

# 4. Separate X and y
X_train = train_data[:, 0:3]
y_train = train_data[:, 3]

X_test = test_data[:, 0:3]
y_test = test_data[:, 3]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

# 5. Feature scaling
train_mean = np.mean(X_train, axis=0)
train_std = np.std(X_train, axis=0)

X_train_scaled = (X_train - train_mean) / train_std
X_test_scaled = (X_test - train_mean) / train_std

print("Training feature mean:", np.round(train_mean, 2))
print("Training feature std:", np.round(train_std, 2))

print("Scaled X_train:")
print(np.round(X_train_scaled, 2))

print("Scaled X_test:")
print(np.round(X_test_scaled, 2))

# 6. Manual prediction model
weights = np.array([100, -5, 20])
intercept = 2500

y_pred = intercept + np.dot(X_test, weights)

# 7. Error calculation
error = y_test - y_pred
absolute_error = np.abs(error)
squared_error = error ** 2

# 8. Metrics
mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
# 9. Results
print("Actual y_test:", y_test)
print("Predicted y_pred:", y_pred)

print("Error:", error)
print("Absolute Error:", absolute_error)
print("Squared Error:", squared_error)

print("MAE:", np.round(mae, 2))
print("MSE:", np.round(mse, 2))
print("RMSE:", np.round(rmse, 2))

if mae <= 100:
    print("Good model")
elif mae <= 200:
    print("Acceptable model")
else:
    print("Model needs improvement")

Original data shape: (10, 4)
X_train shape: (8, 3)
y_train shape: (8,)
X_test shape: (2, 3)
y_test shape: (2,)
Training feature mean: [11.5  32.62 48.25]
Training feature std: [2.29 5.19 5.47]
Scaled X_train:
[[ 1.09 -0.89  1.23]
 [-1.53  1.8  -1.51]
 [-0.65 -0.51 -0.59]
 [ 1.53 -1.08  1.42]
 [-0.22 -0.12 -0.23]
 [-1.09  1.42 -1.14]
 [ 0.65 -0.7   0.69]
 [ 0.22  0.07  0.14]]
Scaled X_test:
[[ 0.22  0.46  0.32]
 [-0.65  0.65 -0.78]]
Actual y_test: [4300. 4050.]
Predicted y_pred: [4525. 4200.]
Error: [-225. -150.]
Absolute Error: [225. 150.]
Squared Error: [50625. 22500.]
MAE: 187.5
MSE: 36562.5
RMSE: 191.21
Acceptable model


In [73]:
import numpy as np

# 1. Create dataset
data = np.array([
    [10, 30, 45, 4200],
    [12, 35, 50, 4300],
    [9, 40, 42, 3900],
    [11, 32, 47, 4100],
    [13, 29, 52, 4500],
    [14, 28, 55, 4600],
    [8, 42, 40, 3700],
    [15, 27, 56, 4700],
    [10, 36, 44, 4050],
    [12, 33, 49, 4350],
    [np.nan, 34, 48, 4250],
    [16, 26, 57, 4800],
    [7, 45, 39, 3600],
    [13, np.nan, 51, 4450],
    [14, 31, 54, 4550]
], dtype=float)

print("Original data:")
print(data)

print("Original data shape:", data.shape)
print("Number of missing values:", np.sum(np.isnan(data)))

# 2. Clean missing values
column_means = np.nanmean(data, axis=0)

data_clean = data.copy()

missing_rows, missing_cols = np.where(np.isnan(data_clean))
data_clean[missing_rows, missing_cols] = column_means[missing_cols]

print("\nColumn means:")
print(np.round(column_means, 2))

print("\nCleaned data:")
print(data_clean)

print("Number of missing values after cleaning:", np.sum(np.isnan(data_clean)))

# 3. Separate X and y
X = data_clean[:, 0:3]
y = data_clean[:, 3]

print("\nX shape:", X.shape)
print("y shape:", y.shape)

# 4. Shuffle data
rng = np.random.default_rng(42)

indices = rng.permutation(len(data_clean))

X_shuffled = X[indices]
y_shuffled = y[indices]

# 5. Train-test split
train_size = int(0.8 * len(X_shuffled))

X_train = X_shuffled[:train_size]
y_train = y_shuffled[:train_size]

X_test = X_shuffled[train_size:]
y_test = y_shuffled[train_size:]

print("\nX_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

# 6. Feature scaling
train_mean = np.mean(X_train, axis=0)
train_std = np.std(X_train, axis=0)

X_train_scaled = (X_train - train_mean) / train_std
X_test_scaled = (X_test - train_mean) / train_std

print("\nTraining mean:", np.round(train_mean, 2))
print("Training std:", np.round(train_std, 2))

print("\nScaled X_train:")
print(np.round(X_train_scaled, 2))

print("\nScaled X_test:")
print(np.round(X_test_scaled, 2))

# 7. Manual linear prediction
weights = np.array([100, -5, 20])
intercept = 2500

y_pred = intercept + np.dot(X_test, weights)

print("\nActual y_test:")
print(y_test)

print("Predicted y_pred:")
print(np.round(y_pred, 2))

# 8. Error calculation
error = y_test - y_pred
absolute_error = np.abs(error)
squared_error = error ** 2

print("\nError:")
print(np.round(error, 2))

print("Absolute error:")
print(np.round(absolute_error, 2))

print("Squared error:")
print(np.round(squared_error, 2))

# 9. Metrics
mae = np.mean(absolute_error)
mse = np.mean(squared_error)
rmse = np.sqrt(mse)
mape = np.mean(np.abs(error / y_test)) * 100

print("\nMAE:", np.round(mae, 2))
print("MSE:", np.round(mse, 2))
print("RMSE:", np.round(rmse, 2))
print("MAPE:", np.round(mape, 2), "%")

# 10. Bad prediction detection
bad_prediction_mask = absolute_error > 200

bad_X = X_test[bad_prediction_mask]
bad_actual = y_test[bad_prediction_mask]
bad_predicted = y_pred[bad_prediction_mask]
bad_error = absolute_error[bad_prediction_mask]

print("\nBad prediction samples:")
print(bad_X)

print("Bad actual values:")
print(bad_actual)

print("Bad predicted values:")
print(np.round(bad_predicted, 2))

print("Bad absolute errors:")
print(np.round(bad_error, 2))

# 11. Final model status
print("\nFinal model status:")

if mape <= 5:
    print("Excellent model")
elif mape <= 10:
    print("Acceptable model")
else:
    print("Model needs improvement")

Original data:
[[  10.   30.   45. 4200.]
 [  12.   35.   50. 4300.]
 [   9.   40.   42. 3900.]
 [  11.   32.   47. 4100.]
 [  13.   29.   52. 4500.]
 [  14.   28.   55. 4600.]
 [   8.   42.   40. 3700.]
 [  15.   27.   56. 4700.]
 [  10.   36.   44. 4050.]
 [  12.   33.   49. 4350.]
 [  nan   34.   48. 4250.]
 [  16.   26.   57. 4800.]
 [   7.   45.   39. 3600.]
 [  13.   nan   51. 4450.]
 [  14.   31.   54. 4550.]]
Original data shape: (15, 4)
Number of missing values: 2

Column means:
[  11.71   33.43   48.6  4270.  ]

Cleaned data:
[[  10.           30.           45.         4200.        ]
 [  12.           35.           50.         4300.        ]
 [   9.           40.           42.         3900.        ]
 [  11.           32.           47.         4100.        ]
 [  13.           29.           52.         4500.        ]
 [  14.           28.           55.         4600.        ]
 [   8.           42.           40.         3700.        ]
 [  15.           27.           56.         4